import json
import os
import re
import requests
import sys

REPO = "attogram/academic-vibing"
SUMMARIES_FILE = "outbox/gh-issue-summaries.json"
TRIAGE_FILE = "TRIAGE_FULL.md"

def get_triage_map():
    triage_map = {}
    if not os.path.exists(TRIAGE_FILE):
        print(f"Warning: {TRIAGE_FILE} not found.")
        return triage_map

    with open(TRIAGE_FILE, 'r') as f:
        content = f.read()

    # Find buckets in TRIAGE_FULL.md
    # Formats expected:
    # - **[OUTLET]** #139, #140
    # - [OUTLET] #139, #140
    buckets = re.findall(r'- \*\*\[(PAPER|OUTLET|NEEDS VERIFICATION|TOO RAW)\]\*\* (.*)', content)
    if not buckets:
        # Try without bold
        buckets = re.findall(r'- \[(PAPER|OUTLET|NEEDS VERIFICATION|TOO RAW)\] (.*)', content)

    for bucket, issues_str in buckets:
        issue_nums = re.findall(r'#(\d+)', issues_str)
        for num in issue_nums:
            triage_map[num.lstrip('0')] = bucket

    return triage_map

def post_to_github(issue_num, bucket, summary, token, dry_run=False):
    comment_body = f"## [TRIAGE]: {bucket}\n\n### [SUMMARY (1k)]\n\n{summary}\n\n---\n*Automated summary generated by Attogram Corpus Postman skill.*"

    if dry_run:
        print(f"[DRY-RUN] Would post to Issue #{issue_num}:")
        print(f"Label: {bucket}")
        print(f"Body: {comment_body[:100]}...")
        return True

    url = f"https://api.github.com/repos/{REPO}/issues/{issue_num}/comments"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }

    response = requests.post(url, headers=headers, json={"body": comment_body})
    if response.status_code == 201:
        print(f"Successfully posted to Issue #{issue_num}")
        return True
    else:
        print(f"Failed to post to Issue #{issue_num}: {response.status_code}")
        print(response.text)
        return False

def main():
    dry_run = "--dry-run" in sys.argv
    token = os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN")

    if not token and not dry_run:
        print("Error: GH_TOKEN or GITHUB_TOKEN environment variable required unless --dry-run is used.")
        sys.exit(1)

    if not os.path.exists(SUMMARIES_FILE):
        print(f"Error: {SUMMARIES_FILE} not found.")
        sys.exit(1)

    with open(SUMMARIES_FILE, 'r') as f:
        summaries = json.load(f)

    triage_map = get_triage_map()

    print(f"Starting GitHub Issue Automation for {len(summaries)} issues...")

    success_count = 0
    for issue_id, summary in summaries.items():
        # issue_id might be "001", lstrip to get "1"
        clean_id = issue_id.lstrip('0')
        bucket = triage_map.get(clean_id, "NEEDS VERIFICATION")

        if post_to_github(clean_id, bucket, summary, token, dry_run):
            success_count += 1

    print(f"Done. Processed {success_count} / {len(summaries)} issues.")

if __name__ == "__main__":
    main()
